### ISSUE TITLE
TypeError: Invalid number of arguments, args should be ['header', 'twist'] args are(None,)

### ISSUE THREAD

**Issue by johagge** [bit-bots/bitbots_behavior#175]
## Expected behavior

no error please :pleading_face: 

## Current behavior

```
[ERROR] [1622924409.123795, 7.840000]: bad callback: <bound method WorldModelCapsule.ball_twist_callback of <bitbots_blackboard.capsules.world_model_capsule.WorldModelCapsule object at 0x7fb620df0f28>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/jonas/catkin_ws/src/bitbots_meta/bitbots_behavior/bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py", line 189, in ball_twist_callback
    self.ball_twist_publisher.publish(self.ball_twist_map)
  File "/opt/ros/melodic/lib/python3/dist-packages/rospy/topics.py", line 879, in publish
    data = args_kwds_to_message(self.data_class, args, kwds)
  File "/opt/ros/melodic/lib/python3/dist-packages/rospy/msg.py", line 122, in args_kwds_to_message
    return data_class(*args)
  File "/opt/ros/melodic/lib/python3/dist-packages/geometry_msgs/msg/_TwistStamped.py", line 71, in __init__
    super(TwistStamped, self).__init__(*args, **kwds)
  File "/opt/ros/melodic/lib/python3/dist-packages/genpy/message.py", line 353, in __init__
    raise TypeError('Invalid number of arguments, args should be %s' % str(self.__slots__) + ' args are' + str(args))
TypeError: Invalid number of arguments, args should be ['header', 'twist'] args are(None,)

```

## Steps to Reproduce

1. I started the simulation in webots
2.
3.
...

## Context (Environment)

- [ ] RViz
- [X] Simulator
- [ ] Robot
- [ ] Local

**Comment by jaagut** [comment]
So is this fixed by #182?
