### ISSUE TITLE
 'BodyBlackboard' object has no attribute 'shut_down_request'

### ISSUE THREAD

**Issue by jgueldenstein** [bit-bots/bitbots_behavior#239]
```
Traceback (most recent call last):
  File "/homes/15guelden/ws/src/bitbots_meta/bitbots_behavior/bitbots_body_behavior/src/bitbots_body_behavior/body_behavior.py", line 79, in <module>
    D.update()
  File "/homes/15guelden/ws/src/bitbots_meta/dynamic_stack_decider/dynamic_stack_decider/src/dynamic_stack_decider/dsd.py", line 238, in update
    result = current_instance.perform()
  File "/homes/15guelden/ws/src/bitbots_meta/dynamic_stack_decider/dynamic_stack_decider/src/dynamic_stack_decider/sequence_element.py", line 28, in perform
    self.current_action.perform()
  File "/homes/15guelden/ws/src/bitbots_meta/bitbots_behavior/bitbots_body_behavior/src/bitbots_body_behavior/actions/play_animation.py", line 27, in perform
    success = self.start_animation(anim)
  File "/homes/15guelden/ws/src/bitbots_meta/bitbots_behavior/bitbots_body_behavior/src/bitbots_body_behavior/actions/play_animation.py", line 61, in start_animation
    while not server_running and not self.blackboard.shut_down_request and not rospy.is_shutdown():
AttributeError: 'BodyBlackboard' object has no attribute 'shut_down_request'
```
## Steps to Reproduce

1. seems to happen if the behavior is faster than the animation server
...

## Context (Environment)

- [ ] RViz
- [ ] Simulator
- [ ] Robot
- [ ] Local

**Comment by jaagut** [comment]
Fixed with #240
