### ISSUE TITLE
Team-ball handling dies

### ISSUE THREAD

**Issue by jaagut** [bit-bots/bitbots_behavior#297]
Behavior dies, when handling a team-ball. This was the error we noticed during our latest HLVS game.

## Expected behavior
Handle team-balls correctly

## Current behavior
```
[body_behavior-32] Traceback (most recent call last):
[body_behavior-32]   File "/colcon_ws/install/bitbots_body_behavior/lib/python3.10/site-packages/bitbots_body_behavior/body_behavior.py", line 84, in loop
[body_behavior-32]     self.dsd.blackboard.pathfinding.calculate_time_to_ball()
[body_behavior-32]   File "/colcon_ws/install/bitbots_blackboard/local/lib/python3.10/dist-packages/bitbots_blackboard/capsules/pathfinding_capsule.py", line 64, in calculate_time_to_ball
[body_behavior-32]     if self._blackboard.world_model.ball_has_been_seen() and \
[body_behavior-32]   File "/colcon_ws/install/bitbots_blackboard/local/lib/python3.10/dist-packages/bitbots_blackboard/capsules/world_model_capsule.py", line 108, in ball_has_been_seen
[body_behavior-32]     return self._blackboard.node.get_clock().now() - self.ball_last_seen() < self.ball_lost_time
[body_behavior-32]   File "/colcon_ws/install/bitbots_blackboard/local/lib/python3.10/dist-packages/bitbots_blackboard/capsules/world_model_capsule.py", line 102, in ball_last_seen
[body_behavior-32]     return max(self.ball_seen_time, self._blackboard.team_data.get_teammate_ball_seen_time())
[body_behavior-32] TypeError: '>' not supported between instances of 'Time' and 'Time'
```

## Steps to Reproduce

1.
2.
3.
...

## Context (Environment)
HLVS Setup, see here: https://data.bit-bots.de/HLVS/2023/GAME_K-GD1-1_2023-03-17-07__itandroids_bitbots_99d633fc05/private_logs/ID_1/docker.log

**Comment by jaagut** [comment]
The whole ball-seen situation needs a refactoring, as it's very scattered.
